CREATE TABLE `actas_conciliaciones_items` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `idActaConciliacion` bigint(20) NOT NULL,
  `FechaFactura` date DEFAULT NULL,
  `MesServicio` int(6) DEFAULT NULL,
  `DepartamentoRadicacion` varchar(90) COLLATE utf8_spanish_ci DEFAULT NULL,
  `NumeroRadicado` varchar(90) COLLATE utf8_spanish_ci DEFAULT NULL,
  `FechaRadicado` date DEFAULT NULL,
  `NumeroContrato` varchar(40) COLLATE utf8_spanish_ci DEFAULT NULL,
  `NumeroFactura` varchar(20) COLLATE utf8_spanish_ci DEFAULT NULL,
  `ValorDocumento` double(15,2) DEFAULT NULL,
  `Impuestos` double(19,2) DEFAULT NULL,
  `TotalPagos` double(19,2) DEFAULT NULL,
  `TotalAnticipos` double(19,2) DEFAULT NULL,
  `TotalCopagos` double(19,2) DEFAULT NULL,
  `DescuentoPGP` double(19,2) DEFAULT NULL,
  `OtrosDescuentos` double(19,2) DEFAULT NULL,
  `AjustesCartera` double(19,2) DEFAULT NULL,
  `TotalGlosaInicial` double(19,2) DEFAULT NULL,
  `TotalGlosaFavor` double(19,2) DEFAULT NULL,
  `TotalGlosaContra` double(15,2) DEFAULT NULL,
  `GlosaXConciliar` double(19,2) DEFAULT NULL,
  `TotalDevoluciones` double(19,2) DEFAULT NULL,
  `ValorSegunEPS` double(19,2) DEFAULT NULL,
  `ValorSegunIPS` double(19,2) DEFAULT NULL,
  `Diferencia` double(19,2) DEFAULT NULL,
  `NoRelacionada` int(1) DEFAULT NULL,
  `idUser` int(11) DEFAULT NULL,
  `FechaRegistro` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `idActaConciliacion` (`idActaConciliacion`),
  KEY `NumeroRadicado` (`NumeroRadicado`),
  KEY `MesServicio` (`MesServicio`),
  KEY `NumeroContrato` (`NumeroContrato`),
  KEY `NumeroFactura` (`NumeroFactura`),
  KEY `NoRelacionada` (`NoRelacionada`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;