CREATE TABLE `copagos_pendientes` (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `NumeroRadicado` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la radicado que genera la EPS',
  `Origen` varchar(10) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Origien',
  `DepartamentoRadicacion` varchar(25) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Departamento donde se radica la cuenta',
  `FechaRadicacion` date NOT NULL COMMENT 'Fecha de Radicacion',
  `Nit_IPS` bigint(20) NOT NULL COMMENT 'Número de identificación del prestador de servicios de salud',
  `RazonSocial` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Razón social o apellidos y nombre del prestador',
  `TipoContrato` varchar(30) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Tipo del contrato',
  `NumeroContrato` varchar(40) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Numero de contrato al que esta sujeto la factura',
  `Valor` double(15,2) NOT NULL COMMENT 'Valor registrado',
  `NumeroRegistros` int(6) DEFAULT NULL COMMENT 'numero de registros',
  `Aplicados` int(6) DEFAULT NULL COMMENT 'aplicados',
  `Errores` int(6) DEFAULT NULL COMMENT 'errores',
  `NoEnviados` int(6) DEFAULT NULL COMMENT 'no enviados',
  `Soporte` varchar(200) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Documento que soporta el cargue ',
  `idUser` int(11) NOT NULL,
  `FechaRegistro` datetime NOT NULL COMMENT 'Fecha que se hace el registro',
  `keyFile` varchar(90) COLLATE utf8_spanish_ci NOT NULL,
  `Sync` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  KEY `NumeroRadicado` (`NumeroRadicado`),
  KEY `Nit_IPS` (`Nit_IPS`),
  KEY `TipoContrato` (`TipoContrato`),
  KEY `NumeroContrato` (`NumeroContrato`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Tabla Envios de copagos';


CREATE TABLE `devoluciones_pendientes` (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `NumeroRadicado` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la radicado que genera la EPS',
  `Origen` varchar(10) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Origien',
  `DepartamentoRadicacion` varchar(25) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Departamento donde se radica la cuenta',
  `FechaRadicacion` date NOT NULL COMMENT 'Fecha de Radicacion',
  `Nit_IPS` bigint(20) NOT NULL COMMENT 'Número de identificación del prestador de servicios de salud',
  `RazonSocial` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Razón social o apellidos y nombre del prestador',
  `TipoContrato` varchar(30) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Tipo del contrato',
  `NumeroContrato` varchar(40) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Numero de contrato al que esta sujeto la factura',
  `Valor` double(15,2) NOT NULL COMMENT 'Valor registrado',
  `NumeroRegistros` int(6) DEFAULT NULL COMMENT 'numero de registros',
  `Aplicados` int(6) DEFAULT NULL COMMENT 'aplicados',
  `Errores` int(6) DEFAULT NULL COMMENT 'errores',
  `NoEnviados` int(6) DEFAULT NULL COMMENT 'no enviados',
  `Soporte` varchar(200) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Documento que soporta el cargue ',
  `idUser` int(11) NOT NULL,
  `FechaRegistro` datetime NOT NULL COMMENT 'Fecha que se hace el registro',
  `keyFile` varchar(90) COLLATE utf8_spanish_ci NOT NULL,
  `Sync` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  KEY `NumeroRadicado` (`NumeroRadicado`),
  KEY `Nit_IPS` (`Nit_IPS`),
  KEY `TipoContrato` (`TipoContrato`),
  KEY `NumeroContrato` (`NumeroContrato`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Tabla Envios de devoluciones';


CREATE TABLE `notas_pendientes` (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `NumeroRadicado` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la radicado que genera la EPS',
  `Origen` varchar(10) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Origien',
  `DepartamentoRadicacion` varchar(25) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Departamento donde se radica la cuenta',
  `FechaRadicacion` date NOT NULL COMMENT 'Fecha de Radicacion',
  `Nit_IPS` bigint(20) NOT NULL COMMENT 'Número de identificación del prestador de servicios de salud',
  `RazonSocial` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Razón social o apellidos y nombre del prestador',
  `TipoContrato` varchar(30) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Tipo del contrato',
  `NumeroContrato` varchar(40) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Numero de contrato al que esta sujeto la factura',
  `Valor` double(15,2) NOT NULL COMMENT 'Valor registrado',
  `NumeroRegistros` int(6) DEFAULT NULL COMMENT 'numero de registros',
  `Aplicados` int(6) DEFAULT NULL COMMENT 'aplicados',
  `Errores` int(6) DEFAULT NULL COMMENT 'errores',
  `NoEnviados` int(6) DEFAULT NULL COMMENT 'no enviados',
  `Soporte` varchar(200) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Documento que soporta el cargue ',
  `idUser` int(11) NOT NULL,
  `FechaRegistro` datetime NOT NULL COMMENT 'Fecha que se hace el registro',
  `keyFile` varchar(90) COLLATE utf8_spanish_ci NOT NULL,
  `Sync` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  KEY `NumeroRadicado` (`NumeroRadicado`),
  KEY `Nit_IPS` (`Nit_IPS`),
  KEY `TipoContrato` (`TipoContrato`),
  KEY `NumeroContrato` (`NumeroContrato`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Tabla Envios de nota credito';


CREATE TABLE `radicadospendientes` (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `NumeroRadicado` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la radicado que genera la EPS',
  `Origen` varchar(10) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Origien',
  `DepartamentoRadicacion` varchar(25) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Departamento donde se radica la cuenta',
  `FechaRadicacion` date NOT NULL COMMENT 'Fecha de Radicacion',
  `Nit_IPS` bigint(20) NOT NULL COMMENT 'Número de identificación del prestador de servicios de salud',
  `RazonSocial` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Razón social o apellidos y nombre del prestador',
  `TipoContrato` varchar(30) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Tipo del contrato',
  `ModalidadContratacion` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Modalidad de la Contratacion',
  `NumeroContrato` varchar(40) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Numero de contrato al que esta sujeto la factura',
  `Valor` double(15,2) NOT NULL COMMENT 'Valor de la factura menos impuestos de ley',
  `EstadoAuditoria` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Estado de auditoria',
  `EstadoRadicacion` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Estado del radicado',
  `FechaAprobacion` date NOT NULL COMMENT 'Fecha de Aprobacion',
  `UsuarioAprobacion` int(20) DEFAULT NULL COMMENT 'usuario de aprobacion',
  `Soporte` varchar(200) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Documento que soporta el cargue ',
  `idUser` int(11) NOT NULL,
  `FechaRegistro` datetime NOT NULL COMMENT 'Fecha que se hace el registro',
  `keyFile` varchar(90) COLLATE utf8_spanish_ci NOT NULL,
  `Sync` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  KEY `NumeroRadicado` (`NumeroRadicado`),
  KEY `Nit_IPS` (`Nit_IPS`),
  KEY `TipoContrato` (`TipoContrato`),
  KEY `NumeroContrato` (`NumeroContrato`),
  KEY `EstadoRadicacion` (`EstadoRadicacion`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Tabla Envios de radicado';


CREATE TABLE `temp_copagos_pendientes` (
  `ID` varchar(1) COLLATE utf8_spanish_ci NOT NULL,
  `NumeroRadicado` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la radicado que genera la EPS',
  `Origen` varchar(10) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Origien',
  `DepartamentoRadicacion` varchar(25) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Departamento donde se radica la cuenta',
  `FechaRadicacion` date NOT NULL COMMENT 'Fecha de Radicacion',
  `Nit_IPS` bigint(20) NOT NULL COMMENT 'Número de identificación del prestador de servicios de salud',
  `RazonSocial` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Razón social o apellidos y nombre del prestador',
  `TipoContrato` varchar(30) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Tipo del contrato',
  `NumeroContrato` varchar(40) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Numero de contrato al que esta sujeto la factura',
  `Valor` double(15,2) NOT NULL COMMENT 'Valor registrado',
  `NumeroRegistros` int(6) DEFAULT NULL COMMENT 'numero de registros',
  `Aplicados` int(6) DEFAULT NULL COMMENT 'aplicados',
  `Errores` int(6) DEFAULT NULL COMMENT 'errores',
  `NoEnviados` int(6) DEFAULT NULL COMMENT 'no enviados',
  `Soporte` varchar(200) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Documento que soporta el cargue ',
  `idUser` int(11) NOT NULL,
  `FechaRegistro` datetime NOT NULL COMMENT 'Fecha que se hace el registro',
  `keyFile` char(90) COLLATE utf8_spanish_ci NOT NULL,
  `Sync` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  KEY `NumeroRadicado` (`NumeroRadicado`),
  KEY `Nit_IPS` (`Nit_IPS`),
  KEY `TipoContrato` (`TipoContrato`),
  KEY `NumeroContrato` (`NumeroContrato`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Tabla Envios de copagos';


CREATE TABLE `temp_devoluciones_pendientes` (
  `ID` varchar(1) COLLATE utf8_spanish_ci NOT NULL,
  `NumeroRadicado` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la radicado que genera la EPS',
  `Origen` varchar(10) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Origien',
  `DepartamentoRadicacion` varchar(25) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Departamento donde se radica la cuenta',
  `FechaRadicacion` date NOT NULL COMMENT 'Fecha de Radicacion',
  `Nit_IPS` bigint(20) NOT NULL COMMENT 'Número de identificación del prestador de servicios de salud',
  `RazonSocial` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Razón social o apellidos y nombre del prestador',
  `TipoContrato` varchar(30) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Tipo del contrato',
  `NumeroContrato` varchar(40) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Numero de contrato al que esta sujeto la factura',
  `Valor` double(15,2) NOT NULL COMMENT 'Valor registrado',
  `NumeroRegistros` int(6) DEFAULT NULL COMMENT 'numero de registros',
  `Aplicados` int(6) DEFAULT NULL COMMENT 'aplicados',
  `Errores` int(6) DEFAULT NULL COMMENT 'errores',
  `NoEnviados` int(6) DEFAULT NULL COMMENT 'no enviados',
  `Soporte` varchar(200) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Documento que soporta el cargue ',
  `idUser` int(11) NOT NULL,
  `FechaRegistro` datetime NOT NULL COMMENT 'Fecha que se hace el registro',
  `keyFile` varchar(90) COLLATE utf8_spanish_ci NOT NULL,
  `Sync` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  KEY `NumeroRadicado` (`NumeroRadicado`),
  KEY `Nit_IPS` (`Nit_IPS`),
  KEY `TipoContrato` (`TipoContrato`),
  KEY `NumeroContrato` (`NumeroContrato`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Tabla Envios de devoluciones';


CREATE TABLE `temp_notas_pendientes` (
  `ID` varchar(1) COLLATE utf8_spanish_ci NOT NULL,
  `NumeroRadicado` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la radicado que genera la EPS',
  `Origen` varchar(10) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Origien',
  `DepartamentoRadicacion` varchar(25) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Departamento donde se radica la cuenta',
  `FechaRadicacion` date NOT NULL COMMENT 'Fecha de Radicacion',
  `Nit_IPS` bigint(20) NOT NULL COMMENT 'Número de identificación del prestador de servicios de salud',
  `RazonSocial` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Razón social o apellidos y nombre del prestador',
  `TipoContrato` varchar(30) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Tipo del contrato',
  `NumeroContrato` varchar(40) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Numero de contrato al que esta sujeto la factura',
  `Valor` double(15,2) NOT NULL COMMENT 'Valor registrado',
  `NumeroRegistros` int(6) DEFAULT NULL COMMENT 'numero de registros',
  `Aplicados` int(6) DEFAULT NULL COMMENT 'aplicados',
  `Errores` int(6) DEFAULT NULL COMMENT 'errores',
  `NoEnviados` int(6) DEFAULT NULL COMMENT 'no enviados',
  `Soporte` varchar(200) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Documento que soporta el cargue ',
  `idUser` int(11) NOT NULL,
  `FechaRegistro` datetime NOT NULL COMMENT 'Fecha que se hace el registro',
  `keyFile` varchar(90) COLLATE utf8_spanish_ci NOT NULL,
  `Sync` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  KEY `NumeroRadicado` (`NumeroRadicado`),
  KEY `Nit_IPS` (`Nit_IPS`),
  KEY `TipoContrato` (`TipoContrato`),
  KEY `NumeroContrato` (`NumeroContrato`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Tabla Envios de nota credito';


CREATE TABLE `temp_radicadospendientes` (
  `ID` varchar(1) COLLATE utf8_spanish_ci NOT NULL,
  `NumeroRadicado` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la radicado que genera la EPS',
  `Origen` varchar(10) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Origien',
  `DepartamentoRadicacion` varchar(25) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Departamento donde se radica la cuenta',
  `FechaRadicacion` date NOT NULL COMMENT 'Fecha de Radicacion',
  `Nit_IPS` bigint(20) NOT NULL COMMENT 'Número de identificación del prestador de servicios de salud',
  `RazonSocial` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Razón social o apellidos y nombre del prestador',
  `TipoContrato` varchar(30) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Tipo del contrato',
  `ModalidadContratacion` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Modalidad de la Contratacion',
  `NumeroContrato` varchar(40) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Numero de contrato al que esta sujeto la factura',
  `Valor` double(15,2) NOT NULL COMMENT 'Valor de la factura menos impuestos de ley',
  `EstadoAuditoria` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Estado de auditoria',
  `EstadoRadicacion` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Estado del radicado',
  `FechaAprobacion` date NOT NULL COMMENT 'Fecha de Aprobacion',
  `UsuarioAprobacion` int(20) DEFAULT NULL COMMENT 'usuario de aprobacion',
  `Soporte` varchar(200) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Documento que soporta el cargue ',
  `idUser` int(11) NOT NULL,
  `FechaRegistro` datetime NOT NULL COMMENT 'Fecha que se hace el registro',
  `keyFile` varchar(90) COLLATE utf8_spanish_ci NOT NULL,
  `Sync` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  KEY `NumeroRadicado` (`NumeroRadicado`),
  KEY `Nit_IPS` (`Nit_IPS`),
  KEY `TipoContrato` (`TipoContrato`),
  KEY `NumeroContrato` (`NumeroContrato`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Tabla Envios de radicado';