CREATE TABLE `retenciones` (
  `ID` int(20) NOT NULL AUTO_INCREMENT,
  `Cuentacontable` bigint(20) NOT NULL COMMENT 'Número de la cuenta contable',
  `ObservacionCuenta` varchar(70) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Observacion de la Cuenta',
  `Nit_IPS` bigint(20) NOT NULL COMMENT 'Número de identificación del prestador de servicios de salud',
  `RazonSocial` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Razón social o apellidos y nombre del prestador',
  `FechaTransaccion` date NOT NULL COMMENT 'Fecha de transaccion de la factura',
  `TipoOperacion` int(5) DEFAULT NULL COMMENT 'Tipo de Operacion',
  `NumeroTransaccion` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la Transaccion',
  `NumeroFactura` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la factura del prestador',
  `Descripcion` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'A quien va facturo docuneto id -nombre- id factura asmet',
  `ValorDebito` double(15,2) NOT NULL COMMENT 'Valor del debito',
  `ValorCredito` double(15,2) NOT NULL COMMENT 'Valor del debito',
  `Saldo` double(15,2) NOT NULL COMMENT 'Saldo',
  `Soporte` varchar(200) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Documento que soporta el cargue ',
  `idUser` int(11) NOT NULL,
  `keyFile` varchar(90) COLLATE utf8_spanish_ci NOT NULL,
  `FechaRegistro` datetime NOT NULL COMMENT 'Fecha que se hace el registro',
  `Sync` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ID`),
  KEY `idUser` (`idUser`),
  KEY `FlagUpdate` (`keyFile`),
  KEY `NumeroFactura` (`NumeroFactura`),
  KEY `FechaTransaccion` (`FechaTransaccion`),
  KEY `TipoOperacion` (`TipoOperacion`),
  KEY `ValorDebito` (`ValorDebito`),
  KEY `ValorCredito` (`ValorCredito`),
  KEY `NumeroTransaccion` (`NumeroTransaccion`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Tabla retenciones generadas';


CREATE TABLE `temporal_retenciones` (
  `ID` varchar(1) COLLATE utf8_spanish_ci NOT NULL,
  `Cuentacontable` bigint(20) NOT NULL COMMENT 'Número de la cuenta contable',
  `ObservacionCuenta` varchar(70) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Observacion de la Cuenta',
  `Nit_IPS` bigint(20) NOT NULL COMMENT 'Número de identificación del prestador de servicios de salud',
  `RazonSocial` varchar(60) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Razón social o apellidos y nombre del prestador',
  `FechaTransaccion` date NOT NULL COMMENT 'Fecha de transaccion de la factura',
  `TipoOperacion` int(5) DEFAULT NULL COMMENT 'Tipo de Operacion',
  `NumeroTransaccion` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la Transaccion',
  `NumeroFactura` varchar(20) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Número de la factura del prestador',
  `Descripcion` varchar(100) COLLATE utf8_spanish_ci NOT NULL COMMENT 'A quien va facturo docuneto id -nombre- id factura asmet',
  `ValorDebito` double(15,2) NOT NULL COMMENT 'Valor del debito',
  `ValorCredito` double(15,2) NOT NULL COMMENT 'Valor del debito',
  `Saldo` double(15,2) NOT NULL COMMENT 'Saldo',
  `Soporte` varchar(200) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Documento que soporta el cargue ',
  `idUser` int(11) NOT NULL,
  `FlagUpdate` int(1) NOT NULL,
  `keyFile` varchar(90) COLLATE utf8_spanish_ci NOT NULL,
  `FechaRegistro` datetime NOT NULL COMMENT 'Fecha que se hace el registro',
  `Sync` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  KEY `idUser` (`idUser`),
  KEY `FlagUpdate` (`FlagUpdate`),
  KEY `NumeroFactura` (`NumeroFactura`),
  KEY `FechaTransaccion` (`FechaTransaccion`),
  KEY `TipoOperacion` (`TipoOperacion`),
  KEY `ValorDebito` (`ValorDebito`),
  KEY `ValorCredito` (`ValorCredito`),
  KEY `NumeroTransaccion` (`NumeroTransaccion`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='Tabla retenciones generadas';